name: flutter_auth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toggle_bar: ^1.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  email_auth: ^0.0.1+2
  email_validator: ^1.0.6
  share: ^0.6.3+5
  flutter_rounded_progress_bar: ^0.2.0
  timer_count_down: ^2.0.0
  assorted_layout_widgets: ^4.0.0
  sortedmap: ^0.4.2+1
  audioplayers: ^0.18.1
  intl: ^0.16.1
  test: ^1.16.5
  mockito: ^4.1.4
  http: ^0.12.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/characters/
    - assets/images/worlds/
    - assets/images/stages/
    - assets/images/levels/World 1/Stage 1/
    - assets/images/levels/World 1/Stage 2/
    - assets/images/levels/World 1/Stage 3/
    - assets/images/levels/World 2/Stage 1/
    - assets/images/levels/World 2/Stage 2/
    - assets/images/levels/World 2/Stage 3/
    - assets/images/levels/World 3/Stage 1/
    - assets/images/levels/World 3/Stage 2/
    - assets/images/levels/World 3/Stage 3/
    - assets/images/monsters/
    - assets/images/
    - assets/icons/
    - assets/audios/battle_music.mp3
    - assets/audios/background_music.mp3
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf

    - family: War Priest Regular
      fonts:
        - asset: assets/fonts/WarPriestRegular-PanE.ttf

    - family: Robus
      fonts:
        - asset: assets/fonts/Robus-Regular.otf

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
